name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          echo "Installed dependencies successfully"
          ls -la node_modules
        
      - name: Build macOS (${{ matrix.arch }})
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "Building version ${VERSION} for ${{ matrix.arch }}"
          npx electron-builder --mac ${{ matrix.arch }} --publish never
          echo "Build completed, checking output:"
          ls -la dist/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-dmg
          path: dist/*.dmg
          retention-days: 1
          if-no-files-found: error 